apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: s3buckets.aws.grepplabs.com
spec:
  group: aws.grepplabs.com
  names:
    kind: S3Bucket
    plural: s3buckets
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            acl:
              description: The canned ACL to apply. Defaults to "private"
              type: string
            bucket:
              description: The name of the bucket
              type: string
            destroyStrategy:
              description: The bucket delete strategy. Defaults to "Delete"
              type: string
            ownershipStrategy:
              description: The bucket ownership strategy. Defaults to "Created"
              type: string
            policy:
              description: A valid bucket policy JSON document
              type: string
            region:
              description: The region to use. Overrides config/env settings
              type: string
            tags:
              description: A mapping of tags to assign to the bucket
              type: object
          required:
          - bucket
          type: object
        status:
          properties:
            arn:
              description: The ARN of the S3 bucket
              type: string
            locationConstraint:
              description: The location contraint of S3 bucket
              type: string
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
