version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/grepplabs/aws-resource-operator
    steps:
      - checkout
      - run:
          name: install kubebuilder
          command: |
            echo 'export KUBEBUILDER_VERSION=1.0.7' >> $BASH_ENV
            echo 'export KUBEBUILDER_DIR=/usr/local/kubebuilder/bin' >> $BASH_ENV
            echo 'export KUBEBUILDER_URL=https://github.com/kubernetes-sigs/kubebuilder/releases/download/v${KUBEBUILDER_VERSION}/kubebuilder_${KUBEBUILDER_VERSION}_linux_amd64.tar.gz' >> $BASH_ENV
            source $BASH_ENV
            sudo sh -c "mkdir -p ${KUBEBUILDER_DIR} && curl -Ls ${KUBEBUILDER_URL} | tar xz --strip-components=2 -C ${KUBEBUILDER_DIR}"
      - run:
          name: build manager
          command: |
            make all

workflows:
  version: 2
  build:
    jobs:
      - build





